# ISSUE 01 on 12/06/2022
## TOPIC: getting error on page 2 running in github codespaces



<details>
<summary>Stacktrace</summary>


```text
TypeError: cannot convert the series to <class 'int'>
Traceback:
File "/home/codespace/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
File "/workspaces/notenrechner-light/frontend/pages/2_ðŸ“ˆ_notenanalyse.py", line 133, in <module>
    fach_datadict[elements] = int(fname_data["fach_id"][i])
File "/home/codespace/.local/lib/python3.10/site-packages/pandas/core/series.py", line 206, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
```

</details>


<details>
<summary>Details</summary>

- This error only occurs after rendering the home page after page 2 has already been loaded once and switching back to page 2 after
- this error can be 'resolved' be reloading the page


</details>




<details>
<summary>Progress</summary>

# This error is still being investigated


</details>
